name: build and push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/devbyteme/byteme-admin_portal_nginx
      TIMESTAMP: ${{ github.run_number }}-${{ github.sha }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Write Secret to File
      #   run: echo "${{ secrets.ENVSECRET }}" > .env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Write Secret to File
        run: echo "${{ secrets.ENVSECRET }}" > .env
      
      - name: Build and push image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL=$(grep VITE_API_BASE_URL .env | cut -d '=' -f2) \
            --build-arg NEXTAUTH_URL=$(grep NEXTAUTH_URL .env | cut -d '=' -f2) \
            -t ${{ env.IMAGE }}:${{ env.TIMESTAMP }} \
            -t ${{ env.IMAGE }}:latest .
      
          docker push ${{ env.IMAGE }}:${{ env.TIMESTAMP }}
          docker push ${{ env.IMAGE }}:latest


    
  deploy:
      runs-on: ubuntu-latest
      needs: build-and-push
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
            chmod 600 ~/.ssh/ec2-key.pem
            ssh-keyscan -H ${{ secrets.PUBLIC_DNS }} >> ~/.ssh/known_hosts

        - name: Run deployment script on EC2
          run: |
            ssh -i ~/.ssh/ec2-key.pem ${{ secrets.SERVER_USER }}@${{ secrets.PUBLIC_DNS }} "cd /var/www/byteme/adminpanel && ./deploy.sh"
